### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by IL-SatoshiAbe** [mizugorou2019/furima-29300#10]
以下の通り提出致します。
挙動確認をよろしくお願い致します。

# URL
https://furima-29300.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin29300
Pass: pass29300

# 出品者用のメールアドレスとパスワード
メールアドレス名: test@test1.com
パスワード: abc123

# 購入者用のメールアドレスとパスワード
メールアドレス: test@test.com
パスワード: abc123

# 購入用カードの番号・期限・セキュリティコード
番号：4242424242424242
期限：2025年12月
セキュリティコード：123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
### [修正箇所]
**①購入時、Githubにご記載いただいたカード情報を入力しても「Token can't be blank」というエラーが出てしまい、購入が完了できないので購入できるようにしましょう**

上記のため、下記の2項目のチェックは次回いたします！
・購入した商品は、再度購入できない状態になっている
・購入が完了したら、トップページまたは購入完了ページに遷移する

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by IL-SatoshiAbe** [comment]
ご指摘ありがとうございます。
該当箇所を修正しましたので、再度ご確認をお願い致します。

# URL
https://furima-29300.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin29300
Pass: pass29300

# 出品者用のメールアドレスとパスワード
メールアドレス名: test@test1.com
パスワード: abc123

# 購入者用のメールアドレスとパスワード
メールアドレス: test@test.com
パスワード: abc123

# 購入用カードの番号・期限・セキュリティコード
番号：4242424242424242
期限：2025年12月
セキュリティコード：123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
